### ISSUE TITLE
curl: Could not resolve host:

### ISSUE THREAD

**Issue by samwel89** [alexylem/jarvis-jeedom#2]
Bonjour,

J'ai un petit souci avec le plugin Jeedom. Avant, je l'ai installé tout seul comme plugin sur Jarvis et çà a bien marché. Je pourrais parler grâce aux interactions crées dans Jeedom. Puis j'ai installé 5 autres plugins; Wikipédia, Gmail, ..... mais les plugins ne marchaient pas, à chaque fois quand je demande wikipédia ou gmail, je réçois que "Je n'ai pas compris la demande" mais Jeedom fonctionnait toujours bien. J'ai décidé de désinstaller Jeedom et puis toutes les autres plugins commençaient à fonctionner. Ensuite, j'ai réinstallé Jeedom, les plugins fonctionnent toujours bien mais Jeedom non plus. Je réçois que curl: Could not resolve host:

Voici une photo qui montre mon problème. Je suis sur RPI 3. Une aide ou les idées svp. Merci d'avance. 

![image](https://cloud.githubusercontent.com/assets/26720867/24369343/f935aaf2-1323-11e7-9d4c-b0587eb750b5.png)

**Comment by alexylem** [comment]
Le problème vient sans aucun doute de l'ordre des plugins que tu peux régler dans:
menu Plugins > Matching Order
Plus d'info sur https://github.com/alexylem/jarvis/issues/220

Pour `curl: Could not resolve host` tu as surement oublié de re-paramétrer le plugin (IP, ...)
Voir https://github.com/alexylem/jarvis/issues/480 et https://github.com/alexylem/jarvis/issues/234

**Comment by samwel89** [comment]
Salut Alex,

Merci pour la réponse rapide...
Yes, it's true that the problem comes from the order of the plugins. I didn't know this functionality before (matching order), that's why i was installing and reinstalling plugins only to change the order :). Thank you.

For the curl problem, It's not true that I forgot the IP, the configuration was fine but I found it strange not to work while I put Jeedom on the bottom of all other plugins. Happily, now it works fine. I uninstalled all plugins, then reinstall only jeedom, it worked, then uninstall and reinstall others, then at last reinstall jeedom and they now work fine all together.

Thanks alot.
