### ISSUE TITLE
Message d'erreur passage d'ordre

### ISSUE THREAD

**Issue by Calaves** [alexylem/jarvis-jeedom#5]
Bonjour,

Je voulais tester ce superbe plugin, jai bien rempli mon adresse ip de jeedom ainsi que l'api key mais lorsque je demande d'effectuer un ordre j'ai ce message d'erreur :  

ERROR: curl: (22) The requested URL returned error: 404 Not Found
HELP: verify jeedom plugin configuration
HELP: troubleshoot by running above curl command in terminal, l'adresse IP est bonne et l'api key aussi, je ne parviens pas à comprendre pourquoi.

Jeedom est installé sur le rpi3 ainsi que jarvis, même en essayant jarvis depuis mon ordi même soucis je dois forcément mal configurer quelque chose mais j'ignore quoi.

Merci par avance.

**Comment by Sweaatchou** [comment]
Salut a tous, pareil ici pour moi. ( je suis sur de ma conf IP api etc... )
difficile de trouver des infos sur la conf de ce plugin... si je comprends bien : 
Dans jeedom j'ai mon interaction fonctionnelle " allumer la tele" 
je la'ai testée dans les interactions de jeedom si j'ecris allumer la tele , elle se lance...
et dans jarvis je fais rien ?
jarvis balance sur le plugin jeedom allumer TV comme dans un terminal?

je vois pas ou sa pêche.

**Comment by Sweaatchou** [comment]
petit UP Svp ....
